#ifndef __XDDOS_MULTIBOOT2_H
#define __XDDOS_MULTIBOOT2_H

#include <multiboot2.h>
typedef struct multiboot_header multiboot_header_t;
typedef struct multiboot_header_tag multiboot_header_tag_t;
typedef struct multiboot_header_tag_information_request multiboot_header_tag_information_request_t;
typedef struct multiboot_header_tag_address multiboot_header_tag_address_t;
typedef struct multiboot_header_tag_entry_address multiboot_header_tag_entry_address_t;
typedef struct multiboot_header_tag_console_flags multiboot_header_tag_console_flags_t;
typedef struct multiboot_header_tag_framebuffer multiboot_header_tag_framebuffer_t;
typedef struct multiboot_header_tag_module_align multiboot_header_tag_module_align_t;
typedef struct multiboot_header_tag_relocatable multiboot_header_tag_relocatable_t;
typedef struct multiboot_color multiboot_color_t;
typedef struct multiboot_mmap_entry multiboot_mmap_entry_t;
typedef struct multiboot_tag multiboot_tag_t;
typedef struct multiboot_tag_string multiboot_tag_string_t;
typedef struct multiboot_tag_module multiboot_tag_module_t;
typedef struct multiboot_tag_basic_meminfo multiboot_tag_basic_meminfo_t;
typedef struct multiboot_tag_bootdev multiboot_tag_bootdev_t;
typedef struct multiboot_tag_mmap multiboot_tag_mmap_t;
typedef struct multiboot_vbe_info_block multiboot_vbe_info_block_t;
typedef struct multiboot_vbe_mode_info_block multiboot_vbe_mode_info_block_t;
typedef struct multiboot_tag_vbe multiboot_tag_vbe_t;
typedef struct multiboot_tag_framebuffer_common multiboot_tag_framebuffer_common_t;
typedef struct multiboot_tag_framebuffer multiboot_tag_framebuffer_t;
typedef struct multiboot_tag_elf_sections multiboot_tag_elf_sections_t;
typedef struct multiboot_tag_apm multiboot_tag_apm_t;
typedef struct multiboot_tag_efi32 multiboot_tag_efi32_t;
typedef struct multiboot_tag_efi64 multiboot_tag_efi64_t;
typedef struct multiboot_tag_smbios multiboot_tag_smbios_t;
typedef struct multiboot_tag_old_acpi multiboot_tag_old_acpi_t;
typedef struct multiboot_tag_new_acpi multiboot_tag_new_acpi_t;
typedef struct multiboot_tag_network multiboot_tag_network_t;
typedef struct multiboot_tag_efi_mmap multiboot_tag_efi_mmap_t;
typedef struct multiboot_tag_efi32_ih multiboot_tag_efi32_ih_t;
typedef struct multiboot_tag_efi64_ih multiboot_tag_efi64_ih_t;
typedef struct multiboot_tag_load_base_addr multiboot_tag_load_base_addr_t;

#endif // !__XDDOS_MULTIBOOT2_H